service: rs-checkout-api
plugins:
  - serverless-offline
provider:
  name: aws
  runtime: nodejs14.x
  region: 'ap-south-1'
functions:
  main:
    handler: dist/main.handler
    events:
      - http:
          method: ANY
          path: /
      - http:
          method: ANY
          path: '{proxy+}'
